name: Bump oxlint

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    branches:
      - 'renovate/oxlint-**'
    paths:
      - package.json

permissions:
  pull-requests: write
  contents: write

env:
  OXLINT_PACKAGE_NAME: oxlint

jobs:
  bump-oxlint-rules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # must use actions/checkout for `git-auto-commit-action` to work

      - name: Install pnpm
        run: corepack enable

      - name: Set node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: pnpm

      - name: Install Dependencies
        run: pnpm i

      - name: Bump oxlint rules
        run: |
          pnpm run clone
          # Generate rules from latest oxlint
          pnpm run generate
          # Update test snapshots
          pnpm run test -u

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'bump oxlint'
